### ISSUE TITLE
Multiple devices in a map

### ISSUE THREAD

**Issue by mokkk** [herverenault/Self-Hosted-GPS-Tracker#14]
Thank you for sharing the useful app! I'm wondering whether I can show several user's locations in the same map and have their ids on the marker. I saw the issues before saying that adding a parameter after the URL can solve the problem. I added in the android app url line, but nothing happened. Did I do it wrong?
Also, my server has the problem of showing the location in different times on different computers, is there a cache problem? Maybe add some codes to solve that？

**Comment by virtadpt** [comment]
It sounds like you're talking about several people running the app independently, but updating the same map.  What you could do is write your back-end so that it requires an API key in the URL to accept map coordinates.  Each user would have a unique API key that differentiates their coordinates in the back-end and changes their marker on the map.  In other words, this is a back-end thing, not a "this app" thing.

That is probably a bug in your map location refresh code, I ran into the same problem.

**Comment by virtadpt** [comment]
This might help explain things: https://github.com/virtadpt/exocortex-halo/blob/master/exocortex_gps_mapper/gps_tracking_server.py

**Comment by mokkk** [comment]
Thanks for the explanation, I'll focus on this direction. By the way,  so did you find the solution to the map location refresh code?

**Comment by virtadpt** [comment]
I did; I sat down with somebody who knows way more about JavaScript than I do and got some help.  Here's the solution (or rather, a solution that works for my use case): https://github.com/virtadpt/exocortex-halo/blob/master/exocortex_gps_mapper/static/gps_tracking_map.html
